# Make a new file with different values to override the defaults.
device_type: cuda

video_constraints: # Use continuity constraints in videos
  use: Yes
  regularization: 0.0001
  frames_before: 0 # Frames to consider before the current frame
  frames_after: 1 # Same with next frames

main: # For the main.py file. Config for the Martinez et al. approach.
  batch_size: 64
  n_epochs: 5 # Number of epochs to execute.
  plot_logs: No # If we should plot images and loss.
  max_video_length: -1 # Maximum length of the video to consider. -1 for all video

hourglass: # For the training of the hourglass model
  data_path: /run/media/bdvllrs/Data/Documents/Supelec/MVA/Image/SURREAL2/data
  data_type: surreal
  n_joints: 24
  run: run0
  batch_size: 4
  n_channels: 256
  n_stack: 2
  n_modules: 2
  n_reductions: 4
